### ISSUE TITLE
Good action for SDK doesn't mentioned?

### ISSUE THREAD

**Issue by boozook** [sayhiben/awesome-playdate#33]
There is good GitHub-action that installs SDK and works on all CI-supported platforms.
[Here it is](https://github.com/marketplace/actions/get-playdate-sdk)

**Comment by sayhiben** [comment]
oh nice, I hadn't seen this

**Comment by boozook** [comment]
Thank you!

**Comment by boozook** [comment]
@sayhiben I've also created #36.
